# Generated by Django 5.0.3 on 2024-03-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название МРО')),
                ('general', models.TextField(verbose_name='общая информация')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=50, verbose_name='id персоны')),
                ('name', models.CharField(max_length=50, verbose_name='имя персоны')),
                ('step', models.IntegerField(verbose_name='позиция персоны')),
            ],
        ),
    ]
