# Generated by Django 5.0.3 on 2024-04-01 08:09

from django.db import migrations
import json


def fill_up_mros(apps, schema_editor):
    with open('Mros.json', 'r') as file:
        info = json.load(file)
    Mro = apps.get_model('viberbotapp', 'Mro')
    Address = apps.get_model('viberbotapp', 'Address')
    for mro in info:
        mro_here = Mro.objects.create(name=mro)
        mro_here.general = info[mro]['general']
        mro_here.save()
        if 'detailed' in info[mro]:
            for key, value in info[mro]['detailed'].items():
                address_here = Address.objects.create(name=value, num=key)
                address_here.department = mro_here
                address_here.save()


class Migration(migrations.Migration):

    dependencies = [
        ('viberbotapp', '0003_address'),
    ]

    operations = [
        migrations.RunPython(fill_up_mros)
    ]
