# Generated by Django 5.0.3 on 2024-04-01 08:16

from django.db import migrations


def change_names(apps, schema_editor):
    Mro = apps.get_model('viberbotapp', 'Mro')
    names = {
        "cheboksarskoe_mro_info": "Чебоксарское МРО",
        'alatyrskoe_mro_info': "Алатырское МРО",
        'batyrevo_mro_info': "Батыревское МРО",
        'kanashskoe_mro_info': "Канашское МРО",
        'novocheboksarskoe_mro_info': "Новочебоксарское МРО",
        'civilskoe_mro_info': "Цивильское МРО",
        'shumerlinskoe_mro_info': "Шумерлинское МРО",
        'yadrinskoe_mro_info': "Ядринское МРО",
        'upravlenie_info': "Управление"
    }
    for key, value in names.items():
        mro_here = Mro.objects.get(name=key)
        mro_here.name = value
        mro_here.save()


class Migration(migrations.Migration):

    dependencies = [
        ('viberbotapp', '0004_auto_20240401_1109'),
    ]

    operations = [
        migrations.RunPython(change_names)
    ]
