# Generated by Django 5.0.3 on 2024-04-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viberbotapp', '0007_alter_person_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='context',
            field=models.TextField(blank=True, null=True, verbose_name='Контекст юзера'),
        ),
    ]
