# Generated by Django 5.0.3 on 2024-04-02 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viberbotapp', '0009_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='адрес счета')),
                ('device_title', models.TextField(verbose_name='Прибор учета')),
                ('modification', models.TextField(verbose_name='Модификация прибора учета')),
                ('serial_number', models.TextField(verbose_name='Серийный номер прибора учета')),
                ('id_device', models.IntegerField(verbose_name='ID счетчика')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='viberbotapp.bill', verbose_name='Лицевой счет')),
            ],
        ),
    ]
