# Generated by Django 5.0.3 on 2024-04-02 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viberbotapp', '0011_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='viberbotapp.bill', verbose_name='Избранный ЛС')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='viberbotapp.person', verbose_name='юзер избранного ЛС')),
            ],
        ),
    ]
