# Generated by Django 5.0.3 on 2024-04-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viberbotapp', '0012_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='prev_step',
            field=models.TextField(blank=True, null=True, verbose_name='Предыдущий шаг'),
        ),
    ]
