# Generated by Django 5.0.3 on 2024-04-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viberbotapp', '0013_person_prev_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='prev_step',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Предыдущий шаг'),
        ),
    ]
