# Generated by Django 5.0.3 on 2024-04-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viberbotapp', '0014_alter_person_prev_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='cost',
            field=models.FloatField(null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='id_indication',
            field=models.IntegerField(null=True, verbose_name='ID показания'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='id_tariff',
            field=models.IntegerField(null=True, verbose_name='ID тарифа'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='readings',
            field=models.IntegerField(null=True, verbose_name='Показания счетчика'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='registration_date',
            field=models.DateTimeField(null=True, verbose_name='Дата приёма'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='title',
            field=models.CharField(max_length=20, null=True, verbose_name='Обозначение'),
        ),
    ]
