# Generated by Django 5.0.3 on 2024-04-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viberbotapp', '0015_alter_rate_cost_alter_rate_id_indication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Второй контекст юзера'),
        ),
    ]
